// Generated by CoffeeScript 1.6.3
(function() {
  var http;

  http = require('http');

  http.get({
    host: 'www.google.com'
  }, function(res) {
    return console.log(res.statusCode);
  });

}).call(this);
